### ISSUE TITLE
Setup Ubuntu/ROS

### ISSUE THREAD

**Issue by guilyx** [master-coro/rtros-management#11]
Sub issue of #3

@sampreets3 to push the Ubuntu/ROS documentation in here, follow these steps : 

1. Pull the current state to your fork | Pull the current state on your local version of the repo
2. Create a new branch (name is ubunturos or ubuntu-ros or whatever you like : meaningfull and short )
3. Start the document.
4. Commit an initial commit for the branch.
5. Open a pull request from your branch to the master-coro/rtros-documentation/master branch. Name it ( "WIP: Document #11"). 
6. Put me as reviewer.
7. Link the project ( in the right tool bar ) and the Issue if it wasn't done automatically ( should be done when you mention #11 in the title )
8. When you're done working on the PR, remove the WIP status in the title and notify me in the comments
9. I merge.

And for every issue we work on we should use those steps to implement, just to get use to the typical Github workflow !

EDIT : you don't have to fork, you can just clone the main repo since we're Maintainers
just do all the steps on this repo instead of your fork.

**Comment by guilyx** [comment]
Use `$ jekyll serve` to get the result of your work on `https://127.0.0.1:4000/rtros-documentation/`

**Comment by sampreets3** [comment]
okay, let me try doing that

**Comment by guilyx** [comment]
Closed in #15
