### ISSUE TITLE
[Report] 05/05 Meeting

### ISSUE THREAD

**Issue by guilyx** [master-coro/rtros-management#17]
# Ubuntu 

# Xenomai 
- Specify versions of Xenomai/Linux Vanilla/IPIPE
- Grub installation
- Troubleshooting file ? Finish the end of tutorial.

# Overview
- Give precision about environment accuracy in µs : which processor ? Features of the computer! 
Comparisons with the same computer, not with different one because of architecture changes!

# ROS Packages
- Classify Packages better ( toolsing, packages )
- Include ROS2  and compare it with ROS

# Purpose
Compare Linux+ROS | Linux+ROS2 | Linux+ROS2+Xenomai

# Metrics
Jitters, Latency

**Comment by guilyx** [comment]
@sampreets3 if you took notes you're welcome to put them here 👍

**Comment by sampreets3** [comment]
**Ubuntu Installation:**
* Specify the target system
* Include screenshots of steps

**Project Overview:**
* Can include what the professor said about why we are doing this project
* Expand the list

**ROS Installation:**
* Include screenshots, specify how to make a choice between the version of ROS
* Talk about simulators, maybe devote a separate page on how to start using ROS

@guilyx I think these are some issues I would like to address
