### ISSUE TITLE
Xenomai Precisions

### ISSUE THREAD

**Issue by guilyx** [master-coro/rtros-management#20]
- [x] Specify versions of Xenomai/Linux Vanilla/IPIPE
- [x] Grub installation ( just link it to Sampreet's post )
- [x] Troubleshooting file ? Finish the end of tutorial.
- [ ] Redo the tutorial following the given steps ( maybe Sampreet could do it )

**Comment by guilyx** [comment]
@sampreets3 do you mention grub anywhere in the doc ?

**Comment by sampreets3** [comment]
@guilyx No I don't think so, not yet. I mean I haven't had to deal with much of grub in ROS or installing Ubuntu. Just the one time when installing in dual-boot, but I guess that is beyond the scope.

**Comment by guilyx** [comment]
https://www.blaess.fr/christophe/2012/07/23/les-latences-de-xenomai/

**Comment by guilyx** [comment]
Error with `make menuconfig` => install bison and flex

**Comment by guilyx** [comment]
Revert CONFIG_CPU_IDLE and CONFIG_ACPI_PROCESSOR because first depends on second
