### ISSUE TITLE
ROS Packages Precisions

### ISSUE THREAD

**Issue by guilyx** [master-coro/rtros-management#22]
- [ ] ROS Stacks classification ( single packages, toolboxes, group of packages [stack] )
- [ ] Include ROS2 research and packages, i.e. probably the one we're going to benchmark
- [ ] Point out the enhancements brought by ROS2 on timing guarantees. (ROS2 is better but it does not provide any hard real-time guarantees.)

**Comment by sampreets3** [comment]
Hey @guilyx I was thinking that since the core ROS fundamentals are beyond the scope of the project, what we could do instead is just a quick walkthrough of how to create a simple publisher-subscriber based application(the "chatter" application). What are your thoughts on that?

**Comment by guilyx** [comment]
We can just add a "important links" rubric leading to official tutorials

**Comment by sampreets3** [comment]
Sure, that sounds even more convenient. On it

**Comment by guilyx** [comment]
https://roscon.ros.org/2015/presentations/RealtimeROS2.pdf

if you need documentation for ROS2

**Comment by guilyx** [comment]
https://www.96boards.org/blog/hikey970-ros2/

**Comment by guilyx** [comment]
I will be able to run the inverted pendulum real time demo I think
