### ISSUE TITLE
[Feature] Github Pages

### ISSUE THREAD

**Issue by guilyx** [master-coro/rtros-management#5]
## Feature Request

Find a good template for github pages and add it here to have a "portfolio" of the project.

**Comment by guilyx** [comment]
Fork
Commit meaningless
Open PR
Link the issue to the PR

**Comment by guilyx** [comment]
Would something like [this](http://madebymunsters.github.io/portfolio-iro/) suit you @sampreets3 ?

**Comment by sampreets3** [comment]
this would be great @Guilyx
